<?php

use Drupal\Core\Form\FormStateInterface;

function fiofio_form_node_page_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    $form['title']['widget'][0]['value']['#title'] = 'Ce que je veux';
    dump($form_id, $form, $form_state, 'module');

    $form['#validate'][] = 'fiofio_validate_my_form';
    $form['actions']['submit']['#submit'][] = 'fiofio_handle_my_form';
}

function fiofio_validate_my_form(&$form, FormStateInterface $form_state) {
    if ($form_state->getValue('title')[0]['value'] === 'toto') {
        $form_state->setErrorByName('title', 'Le titre est vide');
    }
}

function fiofio_handle_my_form(&$form, FormStateInterface $form_state) {
    \Drupal::messenger()->addStatus('Super avec '.$form_state->getValue('title')[0]['value']);
}

function fiofio_theme($existing, $type, $theme, $path) {
    return [
        // Ici, on crée un template réutilisable
        'my_template' => [
            'template' => 'my_template',
            'variables' => [
                'firstname' => '',
            ],
        ],
    ];
}

function fiofio_cron() {
    \Drupal::messenger()->addMessage('Je suis un hook');
}
